### ISSUE TITLE
Unable to connect to OpenVPN management service

### ISSUE THREAD

**Issue by connex91** [brianhornsby/script.openvpn#13]
Hi Brian,

System: ATV1 running latest official openELEC and xbmc.
VPN Provider: PrivateInternetAccess (PIA)
Error message: Unable to connect to OpenVPN management service
Add-On debug: ON
Use Sudo: OFF

I uploaded all the default ovpn configuration files provided by PIA under OPENVPN CONFIGURATION FILES (DEFAULT) https://www.privateinternetaccess.com/openvpn/openvpn.zip

I edited each one of them to add the username/pwd file location (openvpn-pia-login.txt) that is in the same folder as the ovpn file.

When I select a server from the list, I get the error: Unable to connect to OpenVPN management service.

I enabled debugging in the add-on settings but nothing is added to xbmc.log when the error occurs. I deleted xbmc.log and it does not get created when the connection error occurs. 

Any ideas? below is one of the ovpn files

Thanks!
Faustin

client
dev tun
proto udp
remote us-east.privateinternetaccess.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
tls-client
remote-cert-tls server
auth-user-pass openvpn-pia-login.txt
comp-lzo
verb 1
reneg-sec 0

![openvpn-xbmc](https://f.cloud.github.com/assets/287226/1832969/10bd23c2-73c1-11e3-89ce-f385ab7abe63.jpg)

**Comment by helfred** [comment]
Running OpenElec 5.0 on Raspberry Pi with openVPN path = /usr/sbin/openvpn
I'm experiencing the "Unable to connect to OpenVPN Management interface".
It works fine in a terminal with "openvpn xxxxx.ovpn"
"openvpn --version" shows "enable_management=yes"
Have been spending a couple of days on this now and are a little lost :-(  Anybody with the right knowledge?
Br,
Morten

**Comment by ozybard** [comment]
I'm experiencing the same problem with kodibuntu running on a NUC.  Would like this functionality but lack the skills to analyse further.

Any input would be much appreciated.

TIA

ozybard

**Comment by brianhornsby** [comment]
@helfred @ozybard try this [guide](http://forums.tvaddons.ag/threads/24769-How-to-set-up-your-VPN-on-raspberry-pi-using-Brain-Hornsby-Openvpn-for-XBMC)

**Comment by ozybard** [comment]
Hi Brian
Many thanks for the prompt response.
The guide, whilst aimed at RPi installations provided the clue to the solution and I now have VPN working in KodyBuntu.
I will post the steps taken to make this work a little later when I have more time.
Thanks again for your effort on this

Ian B

**Comment by janlde** [comment]
I get the same message on OpenELEC 5.0.1. Done all like described in the post mentioned above. Also the management enable flag is set and all works fine if the client is started manually, so the config seems to be ok.

**Comment by justakiji** [comment]
Im on XBMC openelec and i also get the management not found error. 
"openvpn --version" shows "enable_management=yes"
i tried a lot of the threads about this issue with no luck.

**Comment by ptrixs** [comment]
Hi Brian,

I'm running Kodi on my QNAP NAS.  I installed your addon, configured the settings and pointed to where openvpn is installed (which openvpn command in telnet session to my NAS)

When I run the add-on, it returns the error that about the management interface not being found.

I got the following from the kodi xbmc logs.   Can you advise how to resolve this?  I've read through all the threads and can't seem to get past this.  Much appreciated.

NOTICE: script.openvpn: DEBUG: Addon Id:   [script.openvpn]
NOTICE: script.openvpn: DEBUG: Addon Name: [OpenVPN]
NOTICE: script.openvpn: DEBUG: Version:    [2.1.0]
NOTICE: script.openvpn: DEBUG: OpenVPN:    [usr/sbin/openvpn]
NOTICE: script.openvpn: DEBUG: Userdata:   [/root/.kodi/userdata/addon_data/script.openvpn/]
NOTICE: script.openvpn: DEBUG: OpenVPN Management Interface IP: [192.168.100.10]
NOTICE: script.openvpn: DEBUG: OpenVPN Management Interface Port: [8090]
NOTICE: script.openvpn: DEBUG: OpenVPN Additional Arguments: []
NOTICE: script.openvpn: DEBUG: Sudo: [False]
NOTICE: script.openvpn: DEBUG: Found configuration: [test.ovpn]
 NOTICE: script.openvpn: DEBUG: Response from is_running: [False] [None] [None]
NOTICE: script.openvpn: DEBUG: Select: [test.ovpn]
NOTICE: script.openvpn: DEBUG: Connecting OpenVPN configuration: [test.ovpn]
NOTICE: OpenVPN: DEBUG: OpenVPN: [usr/sbin/openvpn]
NOTICE: OpenVPN: DEBUG: OpenVPN Configuration: [/root/.kodi/userdata/addon_data/script.openvpn/test.ovpn]
NOTICE: OpenVPN: DEBUG: OpenVPN Management IP: [192.168.100.10]
NOTICE: OpenVPN: DEBUG: OpenVPN Management Port: [8090]
NOTICE: OpenVPN: DEBUG: Additional Arguments: []
 NOTICE: OpenVPN: ERROR: OpenVPN: ERROR: Specified OpenVPN does not exist
NOTICE: OpenVPN: DEBUG: Connecting OpenVPN
NOTICE: OpenVPN: DEBUG: [Errno 111] Connection refused
NOTICE: OpenVPN: DEBUG: Command line: ['usr/sbin/openvpn' --cd '/root/.kodi/userdata/addon_data/script.openvpn' --daemon --management 192.168.100.10 8090 --config '/root/.kodi/userdata/addon_data/script.openvpn/test.ovpn' --log '/root/.kodi/userdata/addon_data/script.openvpn/openvpn.log' ]
NOTICE: OpenVPN: ERROR: [Errno 111] Connection refused
NOTICE: OpenVPN: DEBUG: Connect OpenVPN failed

**Comment by brianhornsby** [comment]
Check that your OpenVPN version has the management interface enabled.
Run 'openvpn --version' on you command line and check that compile time defines has "enable_management=yes".

What does it say in the OpenVPN log file (/root/.kodi/userdata/addon_data/script.openvpn/openvpn.log)?
Have you tried running it from the command line with the values used by the script?

FYI I use 127.0.0.1 (localhost) for the management ip and 1337 for the management port.

**Comment by ptrixs** [comment]
enable_management=yes is what I get and there is also nothing in the
script.openvpn folder for logs.

I'm not sure what to run via the command line to try this.

I also tried 127.0.0.1 on port 1337 and it still doesn't connect to
management interface.  I tried to telnet to the NAS on port 1337 and it
doesn't answer.

On Thu, Sep 24, 2015 at 6:20 PM, Brian Hornsby <notifications@github.com>
wrote:

> Check that your OpenVPN version has the management interface enabled.
> Run 'openvpn --version' on you command line and check that compile time
> defines has "enable_management=yes".
>
> What does it say in the OpenVPN log file
> (/root/.kodi/userdata/addon_data/script.openvpn/openvpn.log)?
> Have you tried running it from the command line with the values used by
> the script?
>
> FYI I use 127.0.0.1 (localhost) for the management ip and 1337 for the
> management port.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianhornsby/script.openvpn/issues/13#issuecomment-142852687>
> .
>



-- 

Regards,

Patrick Pierre

**Comment by theincogtion** [comment]
I am running kodi on Rpi 2 with the OS osmc. I loaded a vpn config file but if I try to choose this config for openvpn I get the message from this title. The kodi log:
https://gist.github.com/e772a8442ffc69f1af93.git

I couldn't find any openvpn.log file.

**Comment by harryfine** [comment]
New to the conversation.  Same problem.  Used brian's addon, set it up for Openelec, modified with the files from my VPN provider that I use on my Windows machine, IPVANISH.

Tested with Putty.  Openvpn runs from /usr/sbin.  Configured settings (location etc) with Brian's addon.  Ran the addon, but got the same message:

"unable to connect to openvpn management interface"

Checked the version, it was complied with the management interface equal to YES.  So any ideas would be greatly appreciated.

**Comment by harryfine** [comment]
Just found the fix, at least it worked for me.
Added the line:

management localhost 1337

to the bottom of the ovpn file.  No more error.  Openvpn is running.

Thanks Brian.

**Comment by harryfine** [comment]
Seems although the script is running, as is addon, I'm not getting in.  Log as follows.  Anyone have a hint as to why it's not working?  Certainly some deprecated keynames in the IPVANISH config file.  Found some links online that tls-remote has been changed with VERIFY X509NAME ERROR, and that the syntax must be different.  If true, that's nuts, how can the IPVANISH files be wrong.:

OpenElec:~/.kodi/userdata # openvpn /storage/.config/vpn-config/ipvanish-US-Chicago-chi-a04.ovpn
Tue Oct  6 21:14:49 2015 DEPRECATED OPTION: --tls-remote, please update your configuration
Tue Oct  6 21:14:49 2015 OpenVPN 2.3.5 x86_64-openelec-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [IPv6] built on Mar 31 2015
Tue Oct  6 21:14:49 2015 library versions: LibreSSL 2.1, LZO 2.08
Tue Oct  6 21:14:49 2015 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:1337
Tue Oct  6 21:14:49 2015 WARNING: file '/storage/.config/vpn-config/pass.txt' is group or others accessible
Tue Oct  6 21:14:49 2015 Deprecated TLS cipher name 'DHE-RSA-AES256-SHA', please use IANA name 'TLS-DHE-RSA-WITH-AES-256-CBC-SHA'
Tue Oct  6 21:14:49 2015 Deprecated TLS cipher name 'DHE-DSS-AES256-SHA', please use IANA name 'TLS-DHE-DSS-WITH-AES-256-CBC-SHA'
Tue Oct  6 21:14:49 2015 No valid translation found for TLS cipher 'AES256-SH'
Tue Oct  6 21:14:49 2015 Socket Buffers: R=[212992->131072] S=[212992->131072]
Tue Oct  6 21:14:49 2015 UDPv4 link local: [undef]
Tue Oct  6 21:14:49 2015 UDPv4 link remote: [AF_INET]173.245.202.2:443
Tue Oct  6 21:14:49 2015 TLS: Initial packet from [AF_INET]173.245.202.2:443, sid=053c4891 abdddeda
Tue Oct  6 21:14:49 2015 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Oct  6 21:15:11 2015 VERIFY OK: depth=1, /C=US/ST=FL/L=Winter_Park/O=IPVanish/OU=IPVanish_VPN/CN=IPVanish_CA/emailAddress=support@ipvanish.com
Tue Oct  6 21:15:11 2015 VERIFY X509NAME ERROR: /C=US/ST=FL/L=Winter_Park/O=IPVanish/OU=IPVanish_VPN/CN=chi-a04.ipvanish.com/emailAddress=support@ipvanish.com, must be /storage/.config/vpn-config/chi-a04.ipvanish.com

**Comment by scott012** [comment]
Hello,

I'm also trying to get this to work on Kodibuntu running Isenguard. I receive the same error. I have confirmed the connection works through the terminal.

Has anyone had success running this on Kodibuntu?

Thanks,

Scott

**Comment by scott012** [comment]
Solved my issue - I had followed the guide which said to make sure that "password required" for sudo was left unchecked. I just tried checking it. I was prompted for my sudo password and was then connected to the VPN.

Hope this helps others.

**Comment by rotgutdk** [comment]
@brianhornsby 
Hello Brian,
Thanks for a great plugin! After a lot of work, I finally got it working.
I got the same problem as you mentioned earlier, but I can't get it past the "Unable to connect to openvpn management interface".
When do i openvpn --version, it says "enable_management=yes".
Where do I go from here?
(I am not very sharp on this ssh thing)

I'm on a Raspberry PI2 with OpenELEC installed, and everything went fine untill choosing a VPN to use.

**Comment by robjhynes** [comment]
I'm writing this in Feb 2016 after installing the latest OpenElec on a Raspberry Pi 2.

If you're using OpenElec the OpenVpn binary does not get installed in the regular *nix location.

You can check this on your system by using the which command.

`OpenELEC:~/rob # which openvpn`

I got 

> /storage/.kodi/addons/network.openvpn/bin/openvpn

I then had to edit the following file:

`/storage/.kodi/addons/script.openvpn/resources/settings.xml`

and change the path to the OpenVpn binary to:
`
<setting id="openvpn" type="file" label="2000" default="/storage/.kodi/addons/network.openvpn/bin/openvpn"/>
`

Then it worked. My OpenVpn is a single config file. Brians script read it in without issue and once making the change to the .xml file as per above it all worked perfectly.

Hope this helps.

Rob

**Comment by mborkp** [comment]
Hi Guys,
struggling with the plugin atm
I got enable_management=yes according to openvpn --version, so it is good!
From the logs I'm getting: ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)
and from openvpn --management-client I get:
You must define TUN/TAP device (--dev)
Where do I define the device?

Thanks

**Comment by mborkp** [comment]
Oh, I run Kodi 16 on xbian, Rpi2
Cheers

**Comment by mborkp** [comment]
Right, it works now from under the console, but the plugin still gives me 
ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)
Anyone?
Thanks

**Comment by mborkp** [comment]
got it working by choosing sudo/pass option :)
Is there any way to not to use sudo/pass (bit annoying to enter pass every time)?
Thanks.

**Comment by colinross** [comment]
@mborkp You have to use sudo (as openvpn needs root-level permissions), but you can skip needing a password by using `visudo` to edit your sudoers file and adding
`ALL ALL =NOPASSWD: /usr/sbin/openvpn`

(A cleaner way alternatively is to add this line to its own file in /etc/sudoers.d/)

**Comment by martin-rhodes** [comment]
On OpenElec 6.95.3 (Pi2) I had to change the `openvpn` setting in `~/.kodi/userdata/addon_data/script.openvpn/settings.xml`
to `/usr/bin/openvpn/`

**Comment by snow6oy** [comment]
On my Pi Model B running OSMC had to go the other way
`/usr/sbin/openvpn/`
Thanks @brianhornsby

**Comment by fatso12321** [comment]
After following everything in this thread, I found nothing worked. But I managed to fix it by renaming the password file from pass.txt to pass.conf, and also updating the ovpn file to match, cheers.
