### ISSUE TITLE
Unable to import config from a local path

### ISSUE THREAD

**Issue by chewitt** [brianhornsby/script.openvpn#14]
This is from an OpenELEC 3.2.4 (current stable) system based on Frodo 12.2. The plugin installed correctly and when accessed I am prompted to import an OpenVPN config file. I have two issues:

1.) The base point I am offered to import from is a media mount on a NAS share so I cannot navigate to a local path where I placed the file. It's the same when accessing from the programs menu or accessing addon-settings from the context menu.

Here's a screenshot: http://imgur.com/Tq513al

2.) Even if I move the .conf file to the media share and import it, nothing appears to happen. Renaming the file to .ovpn makes no difference. I have enabled debugging, but I suspect this refers to debug of a connection attempt and we didn't get that far. No python errors are visible in a debug xbmc.log

Please let me know what info I can provide to assist - this looks quite handy and we (the OpenELEC project team) would like to point our users to this script, as long as it works on our OS, and perhaps include this in our "unofficial" plugins repo.

**Comment by xbmcinvisable** [comment]
It's worth noting that openelec are now stopping support for the openvpn client so this will probably be moved the unofficial addons repo. This will need to be installed manually in later versions of openelec.

Only noticed when trying out millhouses test builds on my Rpi v2
