### ISSUE TITLE
vpn xbmc/mac

### ISSUE THREAD

**Issue by kapps7** [brianhornsby/script.openvpn#22]
Brian, thanks for this. Before I give it a go, I just want to know does activate the vpn at the app level ie. xbmc or the entire platform ie. mac ?

Thanks.

**Comment by Trauth69** [comment]
I also have to find <a href="https://www.reviewsdir.com/best-vpn-services/">best vpn service</a> and was looking for information regarding paid ones which offer best services at affordable prices. I don’t have any experience with VPN so any recommendations would be highly appreciated.
