### ISSUE TITLE
Import Key File that is referenced in .ovpn config

### ISSUE THREAD

**Issue by nunnsby** [brianhornsby/script.openvpn#25]
Found an issue in that if you use a separate key-file for authentication, it does not import that file into the script.openvpn directory. It only copies the .ovpn config file. The keyfile has to be manually copied in to the directory.

Yes, I know a keyfile is not very secure, but I do not require encryption, just the tunnel. This way it allows me to stream at virtually full speed on my connection.

Awesome Add-on btw! Thanks ;)

**Comment by xbmcinvisable** [comment]
Can't you edit the ovpn file to to point to location of you key file.
I did a post on a different site it's written to help users on a pi but it explains about editing your opvn files to link to keyfiles.

http://forums.tvaddons.ag/showthread.php?t=24769
