### ISSUE TITLE
OpenVPN

### ISSUE THREAD

**Issue by sorford638** [brianhornsby/script.openvpn#27]
Hi,

I was using OpenVPN fine until I recently changed my router and now KODI says I am connected to the network but the settings states "Internet:Busy" and I am unable to access any online content.  I realise that this is most likely an error with the router but I don't know where to even start in order to solve it.  I'd be very grateful if you could point me in the right direction as your script was working perfectly up until I changed the router.

Thanks,
Steve

**Comment by brianhornsby** [comment]
Sorry, my knowledge of router/network is not that great.
