### ISSUE TITLE
Help (Very new user!)

### ISSUE THREAD

**Issue by eyeballtickler7** [brianhornsby/script.openvpn#29]
Hello, I'm wondering if anyone would be kind enough to help. I am new to the world VPN/Kodi etc.

I have a client (Cloak) on my Mac but am looking to use their openvpn file on my RPI. I have followed the guide to install and configure this script but I can't quite get it to work.

Please see below for my log file, is this suggesting my user id / password is wrong? Or stored incorrectly? Please help

Tue Apr  7 23:12:27 2015 OpenVPN 2.3.5 armv7ve-openelec-linux-gnueabi [SSL (OpenSSL)] [LZO] [EPOLL] [IPv6] built on Mar 31 2015
Tue Apr  7 23:12:27 2015 library versions: LibreSSL 2.1, LZO 2.08
Tue Apr  7 23:12:27 2015 WARNING: file '/storage/.config/vpn-config/pass.txt' is group or others accessible
Tue Apr  7 23:12:27 2015 UDPv4 link local (bound): [undef]
Tue Apr  7 23:12:27 2015 UDPv4 link remote: [AF_INET]184.173.166.155:443
Tue Apr  7 23:12:30 2015 [184.173.166.155] Peer Connection Initiated with [AF_INET]184.173.166.155:443
Tue Apr  7 23:12:32 2015 AUTH: Received control message: AUTH_FAILED
Tue Apr  7 23:12:32 2015 SIGUSR1[soft,auth-failure] received, process restarting
Tue Apr  7 23:12:34 2015 WARNING: file '/storage/.config/vpn-config/pass.txt' is group or others accessible
Tue Apr  7 23:12:34 2015 UDPv4 link local (bound): [undef]
Tue Apr  7 23:12:34 2015 UDPv4 link remote: [AF_INET]184.173.166.155:443
Tue Apr  7 23:12:34 2015 TLS Error: Unroutable control packet received from [AF_INET]184.173.166.155:443 (si=3 op=P_CONTROL_V1)
Tue Apr  7 23:12:44 2015 [184.173.166.155] Peer Connection Initiated with [AF_INET]184.173.166.155:443
Tue Apr  7 23:12:47 2015 AUTH: Received control message: AUTH_FAILED
Tue Apr  7 23:12:47 2015 SIGUSR1[soft,auth-failure] received, process restarting

**Comment by alukach** [comment]
> `Tue Apr 7 23:12:27 2015 WARNING: file '/storage/.config/vpn-config/pass.txt' is group or others accessible`

I believe that this first warning is about permissions. I was having a similar issue (not exactly the same).  Setting the file's permissions to `0600` resolved it.
