### ISSUE TITLE
no http-proxy support?

### ISSUE THREAD

**Issue by rudipereira** [brianhornsby/script.openvpn#30]
Trying to use my Openelec pi from work behind a proxy.
I have tried every possible combination but cannot connect via a proxy, keep getting connection refused and the following error:

"Options error: Unrecognized option or missing parameter(s) in .config/vpn-config/vpnussl.ovpn:1: http-proxy (2.3.5)
Use --help for more information."

I can connect using the same ovpn conf file from windows and kodi running on raspbian.
(in this later case, I first run the openvpn commands and then start kodi)

**Comment by brianhornsby** [comment]
Use the "Additional Arguments" field in setting to add the missing parameter(s) that are required to use http-proxy.
