### ISSUE TITLE
RTNETLINK answers: File exists

### ISSUE THREAD

**Issue by philborman** [brianhornsby/script.openvpn#31]
Not able to set up on OSMC final, but worked on Raspbmc.
OSMC uses connman, which might be the problem?

log shows this...

Fri Jul 10 17:07:06 2015 /sbin/ip route del 0.0.0.0/0
Fri Jul 10 17:07:06 2015 /sbin/ip route add 0.0.0.0/0 via 10.10.2.17
RTNETLINK answers: File exists
Fri Jul 10 17:07:06 2015 ERROR: Linux route add command failed: external program exited with error status: 2

**Comment by MaikoHermans** [comment]
Why was this closed? seems like this problem still exists. I'm running into the same problem and a lot of people with me so it seems

**Comment by brianhornsby** [comment]
It was closed because this is not an issue with the plugin, but with the operation of OpenVPN.
