### ISSUE TITLE
"this add-on can not be configured"

### ISSUE THREAD

**Issue by wade85** [brianhornsby/script.openvpn#32]
Hi All,

installed openVPN tonight to connect my OSMC Raspi to US netflix using netflixmbc - that works on the aussie version.

Connected VPN to PIA's East location. Connection indicated connected. 

SSH'ed in and used curl ipv4.icanhazip.com to get external IP, confirmed US East Coast Based.

Opened Netflixbmc add on, connected all good, opened up my US recent watching listing - this would not appear if it did not connect, then as soon as I select a show to watch, the error is generated by OpenVPN  in the bottom right with the only text as "!" and a pop up titled " Addon" containing "this add-on can not be configured".

Thoughts?

W

**Comment by wade85** [comment]
Hi brain. 

Happy to learn if I did something wrong. Or was there an issue that you fixed ?? 

Wade



 
website |  vCard |  email	

 
mobile +61403956763 
 



On 25 Oct 2015, at 18:17, Brian Hornsby <notifications@github.com> wrote:

Closed #32.

**Comment by brianhornsby** [comment]
Hi,

I decided to have a clear up of issues.
No one else has reported this issue, so decided to close it.
If you are still having issues try reading this guide.
http://brianhornsby.com/blog/how-to-setup-your-vpn-client

Regards

Brian
