### ISSUE TITLE
Username / password

### ISSUE THREAD

**Issue by nadz78** [brianhornsby/script.openvpn#33]
How do you put in the credentials in kodi?

**Comment by brianhornsby** [comment]
What credentials? You shouldn't need to enter a username or password for OpenVPN.

**Comment by nadz78** [comment]
Login & Password, I have a VPN account with TorGuard. On iOS Open VPN allows me to put the username/password and then import the .ovpn files. This works perfectly.
On Kodi (Sideloaded on Amazon FireStick), I spoke to Torguard Helpdesk, they asked me to create a pass.txt file and then edit the  .ovpn to show the path, but still now working. The Pass.txt file was my username and password on 2 separate lines...

The Edited .ovpn file is:
client
dev tun
proto udp
remote ny.east.usa.torguardvpnaccess.com 443
resolv-retry infinite
remote-cert-tls server
nobind
tun-mtu 1500
tun-mtu-extra 32
mssfix 1450
ca /sdcard/ca.crt
auth-user-pass /sdcard/pass.txt
comp-lzo
fast-io
ping-restart 0
route-delay 2
route-method exe
script-security 3 system
mute-replay-warnings
verb 3

**Comment by brianhornsby** [comment]
That looks like an OpenVPN setup issue.
Can you run OpenVPN from the command line? If yes, does it connect ok?
