### ISSUE TITLE
Kodi 15.1 - OpenVPN error  Check the log for more information

### ISSUE THREAD

**Issue by robfed4** [brianhornsby/script.openvpn#34]
I am using a MKIII Android TV box with Kodi 15.1
I downloaded script.openvpn-2.1.0.zip directly from your website and installed with Kodi.
My VPN provider is Torguard and I download the Android OpenVPN config files from torguard.net
I also download the Torguard VPN Android app and I can run this app fine outside of Kodi 

After installing your Kodi OpenVPN add-on, using the configure tile, I imported a couple of Torguard config files and named them accordingly.
I then launched the add-on and I immediately get and error message in the lower right hand corner indicating:  "OpenVPN error  Check the log for more information"

Here is where I get stuck, I don't know where the log file gets written.  I did figure out how to enable "debugging" within your add-on. 

In the file manager of Kodi, I added a source of:  special://logpath 

But nothing apparent seems to be written.

I realize that this are pretty junior questions, but I was wondering if you could provide some additional insight?

**Comment by Qeitr** [comment]
Please answer, same problem here :X when i export my OpenVPN config and try to import it to the addond, this same error pops up..

**Comment by brianhornsby** [comment]
Make sure that you have set the script to point at your openvpn binary in the scripts settings.

**Comment by timanrebel** [comment]
On OSMC (for example) `beautifulsoup ` is not available. I fixed my error by calling:

`sudo apt-get install python-beautifulsoup` via SSH
