### ISSUE TITLE
Automatically start named VPN profile when plugin is loaded

### ISSUE THREAD

**Issue by chewitt** [brianhornsby/script.openvpn#35]
Hello Brian, we point a small but regular number of OpenELEC users in the direction of this plugin from our forums. The consistent follow-up question once they get things working is "How do I make this run automatically on boot?" ..which can be done with a small script, but that rather defeats the point of having a nice GUI plugin for OpenVPN things. I think you'd make a lot of users happy if the plugin could start a named VPN profile on boot. Detecting when the network is up/ready can be tricky on OpenELEC as it boots fast but an option to wait for a configured number of seconds before starting the VPN profile would solve that (we see similar issues with MySQL access, it's simple and tried/tested).

**Comment by xbmcinvisable** [comment]
I've had success connecting to my VPN on boot with the universal autoexec.py script on both OSMC and OpenElec with this built-in Kodi function http://kodi.wiki/view/Autoexec.py, seems that you can also make different autoexec scripts for each profile, on observations it seems to take around 5 seconds from OpenElec home screen before connecting, on OSMC it can take longer 10-15 seconds so I'm 100%  sure if its waiting for network to come up or not, I haven't tried with MySQL.
If you haven't seen it already there is also another small script that may be of interest to you. It's used for automatically switching connections, it's a 3rd party script written by one of the members on the kodi forums http://forum.kodi.tv/showthread.php?tid=222196 Post #35 seems most stable for me.

Regards,
