### ISSUE TITLE
Automatically detect OpenELEC and set correct openvpn location

### ISSUE THREAD

**Issue by chewitt** [brianhornsby/script.openvpn#36]
Hello Brian, the other thing that trips OpenELEC users up is configuring the correct path to the openvpn binary. Since OE 5.0.x we moved openvpn to our unofficial addon repo so once installed the binary path will be /storage/.kodi/addons/network.openvpn/bin/openvpn. If the plugin could check /etc/os-release for NAME="OpenELEC" and pre-set the path it would make setup easier for people.

**Comment by JeromSar** [comment]
Important to note is that because of this, you can no longer find the binary in the KODI file finder. This happens because `.kodi` is a hidden directory, and the file finder does not list hidden directories.

**Comment by chewitt** [comment]
I'm going to close this issue request because LibreELEC adds a symlink from /usr/bin/openvpn to the installed location in /usr/sbin/openvpn explicitly so that script.openvpn finds it without further configuration. I'm not really concerned if things don't work on OpenELEC these days :)

**Comment by JeromSar** [comment]
@chewitt But Brian might be concerned with OpenELEC users?
