### ISSUE TITLE
Kodi 15.1 asus chromebox

### ISSUE THREAD

**Issue by drwar** [brianhornsby/script.openvpn#38]
I have followed your guide to setup Openvpn with the chromebox. Everything went pretty much as outlined for the R pi version. I am using PIA as well so I downloaded your converted files and changed the Pass , certificate and crl.pem files. However when I putty in to test I get an  Error opening configuration file: /Storage/.config/vpn-config/Switzerland.OVPN
If I try and run it from Kodi I get an error trying to access Openvpn management interface.
I am kind of stuck here and could use some guidance getting past this error.

Thanks
Jerry

**Comment by deathbrigner** [comment]
Hi. I have the same problem with Kodi 15.2 on a RPI 2 with your srcipt v3. Everything is ok if go thru ssh but the script is a no go.. I have the same error....

**Comment by drwar** [comment]
Hi, I got mine working except that it like just all of a sudden started working after the third or fourth reboot. The autostart.py script still doesn't work but that I can live with. I am installing on a different machine tomorrow. If I learn anything new as to what the problem is, I will post it.

Jerry

**Comment by drwar** [comment]
deathbrigner,
In going thru a fresh setup and having some issues I happened upon MetalKettle's script for OpenVPN which included PIA support. I installed it and it worked fine. Today I noticed it updated and on checking it out I found that the new version had an autostart feature built in, which for me was great as that was the only feature I was unable to get working in creating my own autoexec.py script. I think you will still have to manually install the OpenVPN binary and you may even have to modify the PIA files as per Brian's very good desrciption. Both of these were done prior to installing Metalkettles version so I cannot tell if they are necessary or not.
~J

**Comment by deathbrigner** [comment]
After fiddling for awhile with a new install at a friend's house we found that the script is always looking in /home/pi/vpn-config/ even if you point the files in another folder in the config.

**Comment by drwar** [comment]
deathbrigner,
That's because you need to go to the kodi/addons/plugin.program.oepia/ directory to see the actual working files in the workingfiles folder. While it will acess whatever link you place in the Autostart.sh in the config folder on startup when you use the addon to change servers it will access the files in that plugin workingfiles folder. If your trying to see this directory by connecting with another computer such as windows you may have to change the samba shares to see it. 

Jerry
