### ISSUE TITLE
OpenElec 6.0.0 openvpn does not work

### ISSUE THREAD

**Issue by jsBlackBelt** [brianhornsby/script.openvpn#39]
Hello Brian,

When trying to install the openvpn script from zip or from your repo, I get an error message that the zip/repo does not have the correct structure..

**Comment by brianhornsby** [comment]
Did you try this zip?
https://github.com/brianhornsby/script.openvpn/releases/download/v3.0.0/script.openvpn-3.0.0.zip

**Comment by jsBlackBelt** [comment]
Yes, I did. Same error.
