### ISSUE TITLE
Kodi complains about incorrect add-on structure and a fix

### ISSUE THREAD

**Issue by alfredomg** [brianhornsby/script.openvpn#41]
Hello,

I attempted to install the latest version of this add-on on a raspberry pi 2 under OSMC (latest version), but Kodi refused to install it and complained saying that the structure of the add-on was incorrect (or something to that effect).

I worked around this problem by unzipping the archive locally, renamed the containing directory from script.openvpn to script.module.openvpn and then rezipped the directory to script.module.openvpn.zip. Kodi happily installed the repackaged add-on. 

Hope this helps other people.

Thanks,
Alfredo

**Comment by rsry** [comment]
Hi Alfredo,

I tried the steps you mentioned in the description and I am still getting the same error. This is on Raspberry Pi running OSMC.

Thanks
Raj

**Comment by alfredomg** [comment]
Hi Raj,

Are you getting the "add-on does not have the correct structure" error?

If so, you should be able to fix the problem with the steps I outlined above. You could also try installing the zip I modified myself, which you can download from here: 

https://www.dropbox.com/s/147hpywim5q7s8r/script.module.openvpn.zip?dl=0

I suggest you to compare the folder in this zip with the original zip.

Thanks,
Alfredo
