### ISSUE TITLE
Kodibuntu requires root password

### ISSUE THREAD

**Issue by bazzlad** [brianhornsby/script.openvpn#42]
Not sure if bug or design, but this when using Kodibuntu 14.0, the VPN will fail unless you have the following checked in the "Script" sections of settings:

1)  "Use sudo when running OpenVPN"
and 
2) "Password is required"

Unchecking "Password is required" causes the script to fail.

Aside from that, it works great - thanks!

**Comment by joswart** [comment]
If you need sudo to start openvpn (which you can check on the console) then the behavior you are seeing is expected and normal.

The options actually do what the system requires them to do ;-)

**Comment by vdeapps** [comment]
For use openvpn with sudo without password, edit this file: `/etc/sudoers.d/openvpn`
And put:
`your_username ALL = NOPASSWD: /usr/sbin/openvpn`

Thus you can run openvpn with your username without password: `sudo openvpn --config openvpnfile`
