### ISSUE TITLE
Configure RPi to only use openvpn

### ISSUE THREAD

**Issue by GonzaloNV** [brianhornsby/script.openvpn#45]
Hello,
firstly, if this is not the right place to ask this questions, please let me know.
Now onto my issue:
I´m using the script on a RPi2 running OSMC. So far I've had no problems with it.
I would like to know if there´s a way I can have osmc only route the traffic through the vpn, as it has happened to me that the vpn somehow falls and I start leaking my ip =(
Could anyone help me with that?

Thanks a lot!

**Comment by jcwchssc** [comment]
I think what you are asking is this: Can I restrict all OSMC traffic to VPN? If VPN goes down, cease all network traffic? Maybe through systemd dependencies? https://wiki.archlinux.org/index.php/systemd

**Comment by GonzaloNV** [comment]
Yes, that's exactly what I want. Though I'm afraid I'm not savy enough to
be able to do anything with that information. So far I'm merely a
follow-a-how-to kind of user...
