### ISSUE TITLE
Way to bulk add .OVPN entries

### ISSUE THREAD

**Issue by jcwchssc** [brianhornsby/script.openvpn#46]
Finally got everything up and running, but would like to avoid using the add-on to add hundreds of OVPN entries. I tried dumping all the .ovpn files to ~/.kodi/userdata/addon_data/script.openvpn - but no dice. Anyone know how the addon grabs those files to display as entries in the addon?

**Comment by joswart** [comment]
I would add one file manually and see where it lands.

It looks like it should land in the folder you just described. But maybe there is a reference in the database as well, that needs to be filled for it to work.
