### ISSUE TITLE
Enter Private Key Password

### ISSUE THREAD

**Issue by kgoerbig** [brianhornsby/script.openvpn#47]
I have 2 Raspberry PI2's. One is for OSMC and the other a OpenVPN server.

My openvpn server on a separate Raspberry PI requires to:

"Enter Private Key Password"

With both CLI and your addon. If I try to initiate a client session with your addon I receive the below prompt while running CLI (putty).

'Password entry required for 'Enter Private Key Password:' (PID 2876).
Please enter password with the systemd-tty-ask-password-agent tool!'

I enabled 'Sudo password' in your addon, but that still did not help. Here is my ovpn config:

client
dev tun
proto udp
remote 192.168.2.20 1194
resolv-retry infinite
nobind
persist-key
persist-tun
mute-replay-warnings
ns-cert-type server
key-direction 1
auth-user-pass /home/osmc/vpn-config/pass.txt
management localhost 1337
cipher AES-128-CBC
comp-lzo
verb 1
mute 20

-----BEGIN CERTIFICATE-----

Cerificate info

</tls-auth>

**Comment by IGSmartthings** [comment]
Did you manage to resolve this issue? I am currently getting the same. 
I need to SSH in the raspberry pi from another machine to enter the key password otherwise the VPN manager does not connect.

**Comment by weado** [comment]
Do you know why ? I'm in the same situation.
