### ISSUE TITLE
Cannot run OpenVPN

### ISSUE THREAD

**Issue by davion24** [brianhornsby/script.openvpn#49]
I continuously receive the error "An error has occurred while trying to connect OpenVPN Unable to connect to OpenVpN management interface"

**Comment by jmnorvell** [comment]
Yes, me too. I'm running the most recent OSMC, via Noobs. I can run OpenVPN successfully from the command line, but the addon gives me that same error every time.

**Comment by JeromSar** [comment]
Possibly related:
```
Sat Sep  3 13:17:36 2016 OpenVPN 2.3.9 armv7ve-openelec-linux-gnueabi [SSL (OpenSSL)] [LZO] [EPOLL] [IPv6] bu                                                    ilt on Jan  6 2016
Sat Sep  3 13:17:36 2016 library versions: LibreSSL 2.1.8, LZO 2.09
Sat Sep  3 13:17:36 2016 neither stdin nor stderr are a tty device and you have neither a controlling tty nor                                                     systemd - can't ask for 'Enter Auth Username:'.  If you used --daemon, you need to use --askpass to make pas                                                    sphrase-protected keys work, and you can not use --auth-nocache.
Sat Sep  3 13:17:36 2016 Exiting due to fatal error

```

Found in 
/storage/.kodi/userdata/addon_data/script.openvpn/openvpn.log

Contents of /etc/os-release
```

NAME="OpenELEC"
VERSION="6.0.3"
ID="openelec"
VERSION_ID="6.0"
PRETTY_NAME="OpenELEC (official) - Version: 6.0.3"
HOME_URL="http://www.openelec.tv"
BUG_REPORT_URL="https://github.com/OpenELEC/OpenELEC.tv"
OPENELEC_ARCH="RPi2.arm"
OPENELEC_BUILD="official"
```

**Comment by kaskavalci** [comment]
any workaround for this issue?

**Comment by oktayaa** [comment]
@JeromSar It is probably not a similar issue. Your config seems to require a password for which there is documentation on this addon's page.

**Comment by oktayaa** [comment]
Guys make sure your openvpn binary is in the right place. Mine was in /usr/sbin instead of /usr/bin and that was the error I was getting.  "An error has occurred while trying to connect OpenVPN Unable to connect to OpenVpN management interface"

I still can't connect but I passed this error.

**Comment by DistantParadox** [comment]
Same issue here.  I changed it to /usr/sbin/openvpn and the error goes away, but the VPN does not connect.
