### ISSUE TITLE
Import config goes to list of repositories 

### ISSUE THREAD

**Issue by ej5921** [brianhornsby/script.openvpn#53]
Hello, I am running Kodi 16.1 on Linux Mint and when I try to Import an OpenVPN configuration file, it takes me straight the list of add-on repositories I have configured in Kodi. I am unable to go 'back' to browse the local filesystem in order to select the .ovpn files I need. I also use this add-on on a RaspberryPi with OpenElec and did not have the issue there. Any ideas why this is happening? Thanks, Edward

**Comment by ej5921** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/5402082/15984783/14966090-2fcf-11e6-9107-6eeb379528c5.png)

**Comment by hoffmeis** [comment]
same problem here on a RaspberryPi with Kodi

**Comment by Schleek** [comment]
I have the same problem as well, tested with 2.1.0 and 3.0.0 on RaspberryPI with OpenELEC (6.0.0)

**Comment by distantsoil** [comment]
For those interested, I had to set up a new location in file manager that went to /storage/.config 
I was then able to select my configuration file

**Comment by oktayaa** [comment]
Same workaround as @distantsoil . I went to Settings/File Manager and added my home directory as a source.

**Comment by CountDantes** [comment]
_(on fire tv stick (1st gen) / running  SPMC 16.6 Jarvis for Amazon Fire TV)_  
Same as  @oktayaa - added the  directory where I had the configuration files and  was able to create multiple choices - **but** when I run the addon and choose a configuration it throws an error and says see log. 
(I'm new to this so take this next thing with a grain of salt:) There's **nothing in the log** about this!
I'll report progress - if I manage any

**Comment by CountDantes** [comment]
Ok - still very unsure of myself here - so again, grain of salt - but it seems like I have a python libraries problem. Not sure I'm reading the log right - here it is:
![image](https://cloud.githubusercontent.com/assets/27148646/24838959/e2b0420a-1d1f-11e7-8f0b-b00887811a38.png)

**Comment by abohler** [comment]
Which version of Kodi are you using?  I am on Krypton 17 and get the same issue.  Reading through the error it doesn't seem to like the file location of the .ovpn.  I have put it in several locations to see if any reacted different sdcard/.ovpn, in various temp folders, etc.

In your log, in previous lines does it say "error getting plugin"?  I have a feeling this may not work in Krypton yet.

ERROR: Control 52 in window 10001 has been asked to focus, but it can't
ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
ERROR: GetDirectory - Error getting plugin://
ERROR: Unable to find plugin
