### ISSUE TITLE
can't access ssh or disable the vpn

### ISSUE THREAD

**Issue by djay** [brianhornsby/script.openvpn#54]
I've successfully instealled openvpn on osmc (kodi on a rasberrypi). However now I can no longer access ssh. It seems even if I don't connect to VPN server my local network has changed such it's not getting routed via my normal DNS and ssh is not able to be connected to. 
Should there not be a setting to disable OpenVPN or use local network?

**Comment by brianhornsby** [comment]
This seems to be a question to ask OSMC not me. 
Closing issue.
