### ISSUE TITLE
OpenVPN with Fire Stick?

### ISSUE THREAD

**Issue by robandroll** [brianhornsby/script.openvpn#58]
Hello, I've only seen references here to OpenELEC and Rasberry. Will this script work on a Fire Stick (Android)? If not, are there any other OpenVPN add-ons out there that will or could this one be modified to do so?

I did install the add-on and was able to import config files, but upon trying to launch the VPN I run into errors in the python script. There are a number of things in the log, but it seems to all boil down to this one: OSError: [Errno 2] No such file or directory.

Any assistance or thoughts would be greatly appreciated!

**Comment by CountDantes** [comment]
(on fire tv stick (1st gen) / running SPMC 16.6 Jarvis for Amazon Fire TV)
First I had the problem reported in #53  
I added the directory where I had the configuration files and was able to create multiple choices - but when I run the addon and choose a configuration it throws an error and says see log.
(I'm new to this so take this next thing with a grain of salt:) There's nothing in the log about this!
I'll report progress - if I manage any

**Comment by IsaacABrown** [comment]
I just tried installing and also was told to see the log when I ran my ovpn file. I don't actually know where to find the log in question though. I did notice that the /usr/bin/openvpn path is probably not going to work and /sdcard/Android/data/org.xbmc.kodi/files doesn't show anything about addons.
