### ISSUE TITLE
Unable to connect to OpenVPN interface service when no prior connection

### ISSUE THREAD

**Issue by Windyo** [brianhornsby/script.openvpn#61]
Hi, 

first thanks for the script.

I've got it "working" in that it detects ongoing connections and allows disconnecting from them.
However I can't switch connections or connect to a new one because when OpenVPN is in a disconnected state, the management interface is unavailable.

I thought it had Something to do with init.d but putting `management localhost 1337` in the optional args section of the /etc/default doesn't change that behavior.

probably just Something to set up on boot but I don't know what. thoughts ?

**Comment by brianhornsby** [comment]
Hi,

The script is basically just a wrapper around a call to the OpenVPN binary, so I suggest you try running it from the command line and see if you get the same issue.

Regards
