### ISSUE TITLE
Will this run on OSX?

### ISSUE THREAD

**Issue by djurrep** [brianhornsby/script.openvpn#64]
Just wondering. 
Will this also work on Mac OSX? For OpenVPN I use Tunnelblick.
It would be nice to be able to start a VPN session from within Kodi (using the iOS Kodi-remote app).
That way I can use the various geo-location restricted add-ons without having to use mouse or keyboard on the Mac to toggle VPN sessions.

**Comment by brianhornsby** [comment]
Yes, but you need to install the openvpn binary.
I used [Homebrew](https://brew.sh) to install it.
