### ISSUE TITLE
.conf files

### ISSUE THREAD

**Issue by tachalainen** [brianhornsby/script.openvpn#65]
Hey!

I'm trying to use a .conf file that my VPN provider provides for connecting to the best suitable VPN server. Everything is working fine when using the .ovpn file connection directly to a specifick server. But, not when using the .conf file. 

Do I need to do something special for this kind of file or doesn't it work at all?

Thanks for you support!

 /

**Comment by brianhornsby** [comment]
Hi,
The script is basically just a wrapper around a call to the OpenVPN binary, so I suggest you try running it from the command line and see if you get the same issue.
Regards

**Comment by tachalainen** [comment]
Aha, ok!
I do a "openvpn /storage/.config/vpn-config/ovpn.conf".
The reply is nothing. Just a new row beneath. Doing the same thing with a ovpn file it starts to connect. So, in this case if I understand this correctly there's no functionality for .conf files in the binary for the openvpn?
